import { lazy, type ComponentType } from 'react';
import { GameComponentProps } from '../types';

export type GameLayoutType = 'square' | 'portrait' | 'landscape';

export interface GameRegistryItem {
  id: string;
  title: string;
  description: string;
  genre: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  thumbnail: string;
  layout: GameLayoutType;
  component: React.LazyExoticComponent<ComponentType<GameComponentProps>>;
  themeColor: string;
  accentShadow: string;
  icon: string;
  controls: string;
  avgDuration: string;
}

export const GAME_REGISTRY: Record<string, GameRegistryItem> = {
  snake: {
    id: 'snake',
    title: 'Pixel Snake',
    description: 'Game ular klasik yang dirombak dengan power-up kecepatan turbo dan neon apple yang bersinar.',
    genre: 'Classic',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_snake_v2/600/450',
    layout: 'square',
    component: lazy(() => import('../components/games/SnakeGame')),
    themeColor: '#22c55e',
    accentShadow: 'shadow-[0_0_15px_rgba(34,197,94,0.15)]',
    icon: '🐍',
    controls: 'Arrows / WASD',
    avgDuration: '2-5 mins'
  },
  brick: {
    id: 'brick',
    title: 'Brick Neon',
    description: 'Hancurkan formasi balok neon dengan pantulan bola berkecepatan tinggi dan kumpulan power-up spektakuler.',
    genre: 'Arcade',
    difficulty: 'Easy',
    thumbnail: 'https://picsum.photos/seed/arcade_brick_v2/600/450',
    layout: 'landscape',
    component: lazy(() => import('../components/games/BrickBreakerGame')),
    themeColor: '#ec4899',
    accentShadow: 'shadow-[0_0_15px_rgba(236,72,153,0.15)]',
    icon: '🧱',
    controls: 'Mouse / Touch',
    avgDuration: '3-10 mins'
  },
  flappy: {
    id: 'flappy',
    title: 'Flappy Pixel',
    description: 'Kepakkan sayap melewati rintangan pipa bercahaya dan kumpulkan koin emas misterius di kota neon.',
    genre: 'Endless',
    difficulty: 'Hard',
    thumbnail: 'https://picsum.photos/seed/arcade_flappy_v2/600/450',
    layout: 'portrait',
    component: lazy(() => import('../components/games/FlappyPixelGame')),
    themeColor: '#eab308',
    accentShadow: 'shadow-[0_0_15px_rgba(234,179,8,0.15)]',
    icon: '🐦',
    controls: 'Space / Tap',
    avgDuration: '1-2 mins'
  },
  space: {
    id: 'space',
    title: 'Space Defender',
    description: 'Pertahankan galaksi dengan menembak jatuh gelombang kapal penyerang alien menggunakan meriam laser plasma.',
    genre: 'Shooter',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_space_v2/600/450',
    layout: 'landscape',
    component: lazy(() => import('../components/games/SpaceDefenderGame')),
    themeColor: '#6366f1',
    accentShadow: 'shadow-[0_0_15px_rgba(99,102,241,0.15)]',
    icon: '🚀',
    controls: 'Arrows + Space',
    avgDuration: '2-5 mins'
  },
  memory: {
    id: 'memory',
    title: 'Memory Grid',
    description: 'Uji daya ingat Anda untuk mencocokkan pasangan kartu retro sebelum sisa waktu Anda habis.',
    genre: 'Puzzle',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_memory_v2/600/450',
    layout: 'square',
    component: lazy(() => import('../components/games/MemoryGridGame')),
    themeColor: '#a855f7',
    accentShadow: 'shadow-[0_0_15px_rgba(168,85,247,0.15)]',
    icon: '🧠',
    controls: 'Mouse / Touch',
    avgDuration: '2-5 mins'
  },
  runner: {
    id: 'runner',
    title: 'Cyber Runner',
    description: 'Berlari tanpa henti melompati duri laser dan menunduk menghindari drone patroli kota cyberpunk.',
    genre: 'Action',
    difficulty: 'Hard',
    thumbnail: 'https://picsum.photos/seed/arcade_runner_v2/600/450',
    layout: 'landscape',
    component: lazy(() => import('../components/games/CyberRunnerGame')),
    themeColor: '#f97316',
    accentShadow: 'shadow-[0_0_15px_rgba(249,115,22,0.15)]',
    icon: '🏃‍♂️',
    controls: 'Arrows / Swipe',
    avgDuration: '2-4 mins'
  },
  pong: {
    id: 'pong',
    title: 'Neon Pong',
    description: 'Uji refleks kilat Anda dalam permainan pingpong arcade klasik melawan kecerdasan bot AI yang taktis.',
    genre: 'Arcade',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_pong_v2/600/450',
    layout: 'landscape',
    component: lazy(() => import('../components/games/NeonPongGame')),
    themeColor: '#3b82f6',
    accentShadow: 'shadow-[0_0_15px_rgba(59,130,246,0.15)]',
    icon: '🏓',
    controls: 'Arrows / WASD',
    avgDuration: '2-5 mins'
  },
  stacker: {
    id: 'stacker',
    title: 'Neon Stacker',
    description: 'Tumpuk balok bergerak tepat di atas satu sama lain setinggi mungkin tanpa menjatuhkan bagian tepi.',
    genre: 'Arcade',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_stacker_v3/600/450',
    layout: 'portrait',
    component: lazy(() => import('../components/games/NeonStackerGame')),
    themeColor: '#f43f5e',
    accentShadow: 'shadow-[0_0_15px_rgba(244,63,94,0.15)]',
    icon: '🧱',
    controls: 'Arrows / WASD',
    avgDuration: '2-5 mins'
  },
  racer: {
    id: 'racer',
    title: 'Vaporwave Racer',
    description: 'Nyetir mobil neon sport menghindari tabrakan lalu lintas di jalan raya cyber bertema vaporwave outrun.',
    genre: 'Action',
    difficulty: 'Hard',
    thumbnail: 'https://picsum.photos/seed/arcade_racer_v2/600/450',
    layout: 'landscape',
    component: lazy(() => import('../components/games/VaporwaveRacerGame')),
    themeColor: '#d946ef',
    accentShadow: 'shadow-[0_0_15px_rgba(217,70,239,0.15)]',
    icon: '🏎️',
    controls: 'Arrows / Swipe',
    avgDuration: '2-4 mins'
  },
  lockbreaker: {
    id: 'lockbreaker',
    title: 'Neon Lock Breaker',
    description: 'Ketuk tepat waktu saat indikator berputar tumpang tindih dengan bulatan gembok untuk memecahkan sandi.',
    genre: 'Arcade',
    difficulty: 'Easy',
    thumbnail: 'https://picsum.photos/seed/arcade_lock_v2/600/450',
    layout: 'square',
    component: lazy(() => import('../components/games/LockBreakerGame')),
    themeColor: '#f59e0b',
    accentShadow: 'shadow-[0_0_15px_rgba(245,158,11,0.15)]',
    icon: '🔐',
    controls: 'Mouse / Touch',
    avgDuration: '3-10 mins'
  },
  sinerider: {
    id: 'sinerider',
    title: 'Sine Rider',
    description: 'Mengapung mengendalikan gelombang sinus melewati celah laser berbahaya dengan fisika halus.',
    genre: 'Arcade',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_sine_v2/600/450',
    layout: 'landscape',
    component: lazy(() => import('../components/games/SineRiderGame')),
    themeColor: '#06b6d4',
    accentShadow: 'shadow-[0_0_15px_rgba(6,182,212,0.15)]',
    icon: '🏄‍♂️',
    controls: 'Arrows / WASD',
    avgDuration: '2-5 mins'
  },
  cosmicdodge: {
    id: 'cosmicdodge',
    title: 'Cosmic Dodge',
    description: 'Geser kapal luar angkasa Anda untuk mengumpulkan bintang jatuh sambil menghindari badai asteroid merah.',
    genre: 'Action',
    difficulty: 'Hard',
    thumbnail: 'https://picsum.photos/seed/arcade_dodge_v2/600/450',
    layout: 'landscape',
    component: lazy(() => import('../components/games/CosmicDodgeGame')),
    themeColor: '#10b981',
    accentShadow: 'shadow-[0_0_15px_rgba(16,185,129,0.15)]',
    icon: '✨',
    controls: 'Arrows / Swipe',
    avgDuration: '2-4 mins'
  },
  lasergrid: {
    id: 'lasergrid',
    title: 'Laser Grid Survival',
    description: 'Melompat antar petak grid 3x3 untuk menghindari barisan laser merah mematikan yang menyala bergantian.',
    genre: 'Arcade',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_grid_v2/600/450',
    layout: 'square',
    component: lazy(() => import('../components/games/LaserGridGame')),
    themeColor: '#ef4444',
    accentShadow: 'shadow-[0_0_15px_rgba(239,68,68,0.15)]',
    icon: '⚡',
    controls: 'Arrows / WASD',
    avgDuration: '2-5 mins'
  },
  simon: {
    id: 'simon',
    title: 'Cyber Simon Says',
    description: 'Hafalkan dan ulangi urutan kedipan lampu neon dengan ketepatan memori kognitif Anda.',
    genre: 'Puzzle',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_simon_v2/600/450',
    layout: 'square',
    component: lazy(() => import('../components/games/CyberSimonGame')),
    themeColor: '#a855f7',
    accentShadow: 'shadow-[0_0_15px_rgba(168,85,247,0.15)]',
    icon: '🧠',
    controls: 'Mouse / Touch',
    avgDuration: '2-5 mins'
  },
  plinko: {
    id: 'plinko',
    title: 'Plinko Neo Arcade',
    description: 'Jatuhkan bola neon melompati ratusan pasak untuk memantul ke saku pengali skor tertinggi.',
    genre: 'Arcade',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_plinko_v2/600/450',
    layout: 'portrait',
    component: lazy(() => import('../components/games/PlinkoNeoGame')),
    themeColor: '#ec4899',
    accentShadow: 'shadow-[0_0_15px_rgba(236,72,153,0.15)]',
    icon: '⚪',
    controls: 'Arrows / WASD',
    avgDuration: '2-5 mins'
  },
  asteroid: {
    id: 'asteroid',
    title: '360° Cosmic Asteroid',
    description: 'Putar kapal jet Anda secara melingkar penuh dan tembaki meteor drifting sebelum menabrak Anda.',
    genre: 'Arcade',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_asteroid_v2/600/450',
    layout: 'square',
    component: lazy(() => import('../components/games/CosmicAsteroidGame')),
    themeColor: '#6366f1',
    accentShadow: 'shadow-[0_0_15px_rgba(99,102,241,0.15)]',
    icon: '🚀',
    controls: 'Arrows / WASD',
    avgDuration: '2-5 mins'
  },
  slasher: {
    id: 'slasher',
    title: 'Cyber Slasher',
    description: 'Geser jari Anda untuk menebas objek neon yang terlontar ke atas secepat kilat sambil menghindari bom.',
    genre: 'Arcade',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_slasher_v2/600/450',
    layout: 'landscape',
    component: lazy(() => import('../components/games/CyberSlasherGame')),
    themeColor: '#d946ef',
    accentShadow: 'shadow-[0_0_15px_rgba(217,70,239,0.15)]',
    icon: '⚔️',
    controls: 'Arrows / WASD',
    avgDuration: '2-5 mins'
  },
  clicker: {
    id: 'clicker',
    title: 'Cyber Clicker',
    description: 'Ekstrak kepingan energi siber dari quantum core secepat mungkin dan beli upgrade pertambangan otomatis.',
    genre: 'Arcade',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_clicker_v1/600/450',
    layout: 'portrait',
    component: lazy(() => import('../components/games/CyberClickerGame')),
    themeColor: '#f59e0b',
    accentShadow: 'shadow-[0_0_15px_rgba(245,158,11,0.15)]',
    icon: '⚡',
    controls: 'Arrows / WASD',
    avgDuration: '2-5 mins'
  },
  blockmatch: {
    id: 'blockmatch',
    title: 'Cyber Block Blast',
    description: 'Hancurkan kelompok blok neon yang berwarna sama dalam jumlah besar untuk melipatgandakan poin combo siber.',
    genre: 'Arcade',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_blocks_v1/600/450',
    layout: 'square',
    component: lazy(() => import('../components/games/BlockMatchGame')),
    themeColor: '#ec4899',
    accentShadow: 'shadow-[0_0_15px_rgba(236,72,153,0.15)]',
    icon: '🧱',
    controls: 'Arrows / WASD',
    avgDuration: '2-5 mins'
  },
  typer: {
    id: 'typer',
    title: 'Cyber Typer Detector',
    description: 'Ketik cepat kata-kata neon yang meluncur turun untuk meledakkannya sebelum menembus firewall pertahanan Anda.',
    genre: 'Arcade',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_typing_v1/600/450',
    layout: 'landscape',
    component: lazy(() => import('../components/games/CyberTyperGame')),
    themeColor: '#6366f1',
    accentShadow: 'shadow-[0_0_15px_rgba(99,102,241,0.15)]',
    icon: '⌨️',
    controls: 'Arrows / WASD',
    avgDuration: '2-5 mins'
  },
  maze: {
    id: 'maze',
    title: 'Cyber Labyrinth Run',
    description: 'Arahkan kapsul siber melewati labirin acak berliku menuju portal keluar bercahaya ungu neon.',
    genre: 'Arcade',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_maze_v1/600/450',
    layout: 'square',
    component: lazy(() => import('../components/games/MazeRunnerGame')),
    themeColor: '#10b981',
    accentShadow: 'shadow-[0_0_15px_rgba(16,185,129,0.15)]',
    icon: '🧭',
    controls: 'Arrows / WASD',
    avgDuration: '2-5 mins'
  },
  matrixmemory: {
    id: 'matrixmemory',
    title: 'Cyber Matrix Memory',
    description: 'Uji kekuatan ingatan spasial Anda dengan menebak letak grid siber biru yang menyala sekejap.',
    genre: 'Puzzle',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_matrix_v1/600/450',
    layout: 'square',
    component: lazy(() => import('../components/games/MemoryPathGame')),
    themeColor: '#06b6d4',
    accentShadow: 'shadow-[0_0_15px_rgba(6,182,212,0.15)]',
    icon: '🧠',
    controls: 'Mouse / Touch',
    avgDuration: '2-5 mins'
  },
  rhythm: {
    id: 'rhythm',
    title: 'Cyber Rhythm Beats',
    description: 'Ketik tombol D, F, J, K tepat waktu sesuai dengan ritme not musik siber yang berjatuhan dinamis.',
    genre: 'Arcade',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_rhythm_v1/600/450',
    layout: 'portrait',
    component: lazy(() => import('../components/games/RhythmTapGame')),
    themeColor: '#d946ef',
    accentShadow: 'shadow-[0_0_15px_rgba(217,70,239,0.15)]',
    icon: '🎵',
    controls: 'Arrows / WASD',
    avgDuration: '2-5 mins'
  },
  puttgolf: {
    id: 'puttgolf',
    title: 'Neon Putt Physics',
    description: 'Gunakan tarikan ketapel fisik dengan memantulkan bola siber melewati dinding untuk masuk ke lubang hitam.',
    genre: 'Arcade',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_golf_v1/600/450',
    layout: 'portrait',
    component: lazy(() => import('../components/games/PixelGolfGame')),
    themeColor: '#a855f7',
    accentShadow: 'shadow-[0_0_15px_rgba(168,85,247,0.15)]',
    icon: '⛳',
    controls: 'Arrows / WASD',
    avgDuration: '2-5 mins'
  },
  dinorun: {
    id: 'dinorun',
    title: 'Cyber Dino Run',
    description: 'Lompati barisan pengaman merah dan merunduk di bawah drone siber yang melesat dalam uji kecepatan tanpa akhir.',
    genre: 'Arcade',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_dino_v1/600/450',
    layout: 'landscape',
    component: lazy(() => import('../components/games/PixelDinoGame')),
    themeColor: '#22c55e',
    accentShadow: 'shadow-[0_0_15px_rgba(34,197,94,0.15)]',
    icon: '🦖',
    controls: 'Arrows / WASD',
    avgDuration: '2-5 mins'
  },
  tetris: {
    id: 'tetris',
    title: 'Cyber Block Puzzle',
    description: 'Klasik Tetris siber! Tumpuk dan rapikan barisan balok neon yang jatuh untuk membersihkan jalur grid penuh.',
    genre: 'Puzzle',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_tetris_v1/600/450',
    layout: 'portrait',
    component: lazy(() => import('../components/games/CyberTetrisGame')),
    themeColor: '#3b82f6',
    accentShadow: 'shadow-[0_0_15px_rgba(59,130,246,0.15)]',
    icon: '🧱',
    controls: 'Mouse / Swipe',
    avgDuration: '5-15 mins'
  },
  archery: {
    id: 'archery',
    title: 'Cyber Orb Archery',
    description: 'Arahkan meriam laser siber Anda dan tembak bola gelembung yang melambung di udara hingga pecah berkeping-keping.',
    genre: 'Arcade',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_archery_v1/600/450',
    layout: 'landscape',
    component: lazy(() => import('../components/games/ArcheryNeoGame')),
    themeColor: '#ec4899',
    accentShadow: 'shadow-[0_0_15px_rgba(236,72,153,0.15)]',
    icon: '🎯',
    controls: 'Arrows / WASD',
    avgDuration: '2-5 mins'
  },
  mines: {
    id: 'mines',
    title: 'Cyber Mines',
    description: 'Bongkar ladang ranjau siber dengan logika dan intuisi. Gunakan bendera merah untuk menandai ranjau yang berbahaya.',
    genre: 'Puzzle',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_mines_v1/600/450',
    layout: 'square',
    component: lazy(() => import('../components/games/CyberMinesGame')),
    themeColor: '#22d3ee',
    accentShadow: 'shadow-[0_0_15px_rgba(34,211,238,0.15)]',
    icon: '💣',
    controls: 'Mouse / Swipe',
    avgDuration: '5-15 mins'
  },
  '2048': {
    id: '2048',
    title: 'Neon 2048',
    description: 'Geser dan gabungkan kotak neon untuk mencapai angka ajaib 2048 sebelum seluruh grid macet dan terkunci total.',
    genre: 'Puzzle',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_2048_v1/600/450',
    layout: 'square',
    component: lazy(() => import('../components/games/Neon2048Game')),
    themeColor: '#c084fc',
    accentShadow: 'shadow-[0_0_15px_rgba(192,132,252,0.15)]',
    icon: '🔢',
    controls: 'Mouse / Swipe',
    avgDuration: '5-15 mins'
  },
  whack: {
    id: 'whack',
    title: 'Whack-A-Drone',
    description: 'Pukul drone yang bermunculan secara acak dengan refleks kilat untuk mengumpulkan poin sebanyak mungkin.',
    genre: 'Arcade',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_whack_v1/600/450',
    layout: 'square',
    component: lazy(() => import('../components/games/WhackADroneGame')),
    themeColor: '#a3e635',
    accentShadow: 'shadow-[0_0_15px_rgba(163,230,53,0.15)]',
    icon: '🔨',
    controls: 'Arrows / WASD',
    avgDuration: '2-5 mins'
  },
  jumprope: {
    id: 'jumprope',
    title: 'Cyber Jump Rope',
    description: 'Lompati rintangan laser siber dengan tepat waktu! Jangan sampai tertangkap!',
    genre: 'Arcade',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_jump_v1/600/450',
    layout: 'landscape',
    component: lazy(() => import('../components/games/JumpRopeGame')),
    themeColor: '#818cf8',
    accentShadow: 'shadow-[0_0_15px_rgba(129,140,248,0.15)]',
    icon: '🏃',
    controls: 'Space / Up',
    avgDuration: '2-5 mins'
  },
  neondrift: {
    id: 'neondrift',
    title: 'Neon Drift',
    description: 'Bermanuver menghindari rintangan neon yang berjatuhan dari atas secepat kilat!',
    genre: 'Action',
    difficulty: 'Hard',
    thumbnail: 'https://picsum.photos/seed/arcade_drift_v1/600/450',
    layout: 'landscape',
    component: lazy(() => import('../components/games/NeonDriftGame')),
    themeColor: '#22d3ee',
    accentShadow: 'shadow-[0_0_15px_rgba(34,211,238,0.15)]',
    icon: '🏎️',
    controls: 'Left / Right',
    avgDuration: '2-5 mins'
  },
  'neon-heist': {
    id: 'neon-heist',
    title: 'Neon Heist',
    description: 'Infiltrasi fasilitas berkeamanan tinggi, retas terminal data, hindari patroli penjaga dan laser!',
    genre: 'Stealth / Strategy',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_heist_v1/600/450',
    layout: 'landscape',
    component: lazy(() => import('../components/games/NeonHeistGame')),
    themeColor: '#06b6d4',
    accentShadow: 'shadow-[0_0_15px_rgba(6,182,212,0.15)]',
    icon: '🥷',
    controls: 'WASD / Mouse',
    avgDuration: '2-5 mins'
  },
  'void-survivor': {
    id: 'void-survivor',
    title: 'Void Survivor',
    description: 'Bertahan hidup melawan gelombang gerombolan makhluk void dengan senjata otomatis dan upgrade acak.',
    genre: 'Roguelite / Survival',
    difficulty: 'Hard',
    thumbnail: 'https://picsum.photos/seed/arcade_void_v1/600/450',
    layout: 'landscape',
    component: lazy(() => import('../components/games/VoidSurvivorGame')),
    themeColor: '#a855f7',
    accentShadow: 'shadow-[0_0_15px_rgba(168,85,247,0.15)]',
    icon: '⚔️',
    controls: 'WASD / Arrows',
    avgDuration: '5-15 mins'
  },
  'orbital-defense': {
    id: 'orbital-defense',
    title: 'Orbital Defense',
    description: 'Bangun dan upgrade menara pertahanan taktis di orbit luar angkasa untuk membendung invasi drone.',
    genre: 'Tower Defense',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_orbital_v1/600/450',
    layout: 'landscape',
    component: lazy(() => import('../components/games/OrbitalDefenseGame')),
    themeColor: '#38bdf8',
    accentShadow: 'shadow-[0_0_15px_rgba(56,189,248,0.15)]',
    icon: '🛰️',
    controls: 'Mouse / Click',
    avgDuration: '5-10 mins'
  },
  'gravity-shift': {
    id: 'gravity-shift',
    title: 'Gravity Shift',
    description: 'Balikkan gravitasi atas-bawah dalam labirin rintangan presisi berkecepatan tinggi.',
    genre: 'Platformer / Precision',
    difficulty: 'Hard',
    thumbnail: 'https://picsum.photos/seed/arcade_gravity_v1/600/450',
    layout: 'landscape',
    component: lazy(() => import('../components/games/GravityShiftGame')),
    themeColor: '#06b6d4',
    accentShadow: 'shadow-[0_0_15px_rgba(6,182,212,0.15)]',
    icon: '🌌',
    controls: 'A/D + Space',
    avgDuration: '2-6 mins'
  },
  'hex-dominion': {
    id: 'hex-dominion',
    title: 'Hex Dominion',
    description: 'Kuasai peta grid heksagonal strategis melawan AI komandan taktis dengan pasukan siber.',
    genre: 'Strategy / Turn-Based',
    difficulty: 'Medium',
    thumbnail: 'https://picsum.photos/seed/arcade_hex_v1/600/450',
    layout: 'landscape',
    component: lazy(() => import('../components/games/HexDominionGame')),
    themeColor: '#6366f1',
    accentShadow: 'shadow-[0_0_15px_rgba(99,102,241,0.15)]',
    icon: '🔷',
    controls: 'Mouse / Click',
    avgDuration: '5-12 mins'
  }
};
